### ISSUE TITLE
マイグレーションエラー

### ISSUE THREAD

**Issue by eRy-sk** [pmo23/basketball#1]
こんにちは、Qiitaでのコメントありがとうございます。
再現を取ろうと環境を立ち上げる途中でマイグレーションエラーが発生したので共有しておきます。

```bash
$ rails db:migrate
...
== 20190209101430 AddIndexToMessage: migrating ================================
-- add_index(:messages, [:room_id, :created_at])
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Key column 'room_id' doesn't exist in table: CREATE  INDEX `index_messages_on_room_id_and_created_at`  ON `messages` (`room_id`, `created_at`) 
/Users/rhiroe/ghq/github.com/pmo23/basketball/db/migrate/20190209101430_add_index_to_message.rb:3:in `change'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/rails:9:in `<top (required)>'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Key column 'room_id' doesn't exist in table: CREATE  INDEX `index_messages_on_room_id_and_created_at`  ON `messages` (`room_id`, `created_at`) 
/Users/rhiroe/ghq/github.com/pmo23/basketball/db/migrate/20190209101430_add_index_to_message.rb:3:in `change'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/rails:9:in `<top (required)>'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Key column 'room_id' doesn't exist in table
/Users/rhiroe/ghq/github.com/pmo23/basketball/db/migrate/20190209101430_add_index_to_message.rb:3:in `change'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/rails:9:in `<top (required)>'
/Users/rhiroe/ghq/github.com/pmo23/basketball/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

`messages`テーブルに`room_id`カラムがないですよとのことみたいですね。
存在しないはずの`room_id`カラムにインデックスを貼ろうとしているからでしょうか。

```rb
# schema.rb

create_table "messages", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
  t.text "content"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["created_at"], name: "index_messages_on_room_id_and_created_at"
end
```

確かに`room_id`は無いようです...。
マイグレーションファイルを消したりだとか、何か思い当たる節はございませんか？

**Comment by eRy-sk** [comment]
`db/migrate/20190211123857_remove_room_id_from_message.rb`
途中でカラムを削除したみたいですね。
カラムを削除する前に貼ったインデックスが残っているんでしょうか？

**Comment by eRy-sk** [comment]
マイグレーションファイルを見る限りカラム周りで色々試行錯誤されたようですね。
モデル構築は構築前に仕様を固めて構築した方がよいです。
まだ開発段階でデータのリセットが可能であればDBを再構築した方が良いかもしれませんね。
マイグレーションファイルは少ないに越したことはありません。
マイグレーションファイルを追加してのカラムの追加や編集は、
リリース後にDBリセットできない故仕方なく行う処置なので、
リセット可能であれば１からやり直すのが良いかと思います。

**Comment by eRy-sk** [comment]
修正して作り直したので権限もらえればプルリク投げます。
